### ISSUE TITLE
The builtins directory keeps main in another file, so 47 cases cannot link

### ISSUE THREAD

**Issue by tamnd** [tamnd/rucc-compat#110]
Every case under `gcc.c-torture/execute/builtins` keeps `main` in `lib/main.c` and its helpers in the other files of `lib`, and a case here is compiled on its own, so the link fails with an undefined reference to `main`. The reference compiler fails the same way, so the harness files them under skipped because the reference cannot pass them either, which is true of the command line it built and false about gcc.

That is 59 cases, each with a `-lib.c` companion beside it, and they are not marginal ones. The `_chk` group that tamnd/rucc#225 is about is sixteen of them, `abs-3.c` and `uabs-3.c` are two more and were the reason this came up: both build and run correctly under rucc after tamnd/rucc#1263, checked by hand at `-O0`, `-O1` and `-O2` with `lib/main.c` on the command line, and the harness reports neither as a pass.

It matters to tamnd/rucc#392 line 4, which says every skip entry has to name a reason about the reference compiler rather than about rucc. These name a reason about the harness, which is the one shape of skip that line exists to keep out, and the count is large enough to move the census.

What a case needs is a way to say which other files of the corpus go on its command line. The gcc suite decides it by directory, so the smallest thing that works is a manifest rule naming a directory and the files every case in it links against, rather than a per case list of 59 entries. `lib/main.c` is the one every one of them needs; several also want `lib/chk.c`, `lib/memcpy.c` and the rest of that directory, and the suite's own runner solves it by compiling the whole `lib` directory once and linking all of it, which is the rule to copy.

The same shape would answer tamnd/rucc-compat#39, which is about libraries rather than about source files but is the same missing sentence in the manifest: here is what else goes on the command line.
